
CREATE TABLE public.presentation_slides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slide_order integer NOT NULL DEFAULT 0,
  layout_type text NOT NULL DEFAULT 'statement',
  title text NOT NULL DEFAULT '',
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.presentation_slides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read slides" ON public.presentation_slides FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Auth insert slides" ON public.presentation_slides FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update slides" ON public.presentation_slides FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete slides" ON public.presentation_slides FOR DELETE TO authenticated USING (true);

INSERT INTO public.presentation_slides (slide_order, layout_type, title, content) VALUES
(0, 'hero', 'Pare de abraçar a loucura e beijar o caos.', '{"subtitle":"Gestão com Inteligência Artificial para empresas que querem crescer com processos, dados e direção.","highlight":"e beijar o caos.","badges":["Grupo GSN","+2.206 empresas","60 profissionais","Brasil & Portugal"]}'::jsonb),
(1, 'statement', 'Em 2026, empresas não vão quebrar por falta de vendas.', '{"tag":"O Problema Real","body":"Vão quebrar por falta de processos e DIREÇÃO.\n\nSe você lidera um time — seja no comercial, financeiro ou operação — todo mundo precisa falar a mesma língua: a língua do lucro.\n\nSenão, você está com um balde furado."}'::jsonb),
(2, 'stats', 'Os números não mentem.', '{"tag":"O Custo do Caos","stats":[{"value":"72%","label":"das PMEs não sabem sua margem de lucro real"},{"value":"16h","label":"por semana gastas apagando incêndios"},{"value":"3x","label":"mais chances de falência sem processos"},{"value":"68%","label":"dos funcionários executam sem padrão definido"}]}'::jsonb),
(3, 'split', 'Você se reconhece aqui?', '{"tag":"Dores do Empresário","subtitle":"A sensação de estar sempre apagando incêndio enquanto a empresa exige que você seja o engenheiro, não o bombeiro.","items":["Carrego o piano sozinho enquanto o ano acelera.","Processos travados, líderes batendo cabeça.","Não importa quanto eu explique, cada um executa como quer.","Vivo no sobe e desce — nunca sei quanto vai entrar.","Não consigo tirar férias. Sem mim, tudo para."]}'::jsonb),
(4, 'cards', 'Você promete o telhado, mas começa por ele.', '{"tag":"Dores do Consultor","cards":[{"title":"Escravo da Entrega","desc":"12-16 horas por dia fazendo o operacional pelo cliente. Sem tempo livre, sem escala."},{"title":"Vende Horas, Não Resultados","desc":"Tenta sustentar o projeto no braço, sem indicadores e sem processos automatizados."},{"title":"Sem Fundamento","desc":"Sem um método que rode sem você, não há margem de lucro que resista."}],"footer":"\"Por que eu não consigo escalar minha consultoria e ter mais tempo livre?\""}'::jsonb),
(5, 'cards', 'O Grupo GSN por trás do Orbit.', '{"tag":"Quem Somos","cards":[{"title":"Templum Consultoria","desc":"Referência nacional em implementação de sistemas de gestão com base em normas ISO. Mais de 8.000 clientes atendidos em todo o Brasil.","badge":"Fundada em 1994 · Líder em ISO"},{"title":"Evolutto","desc":"Plataforma que digitaliza e escala consultorias. Presença em todo o Brasil e Portugal. Transformando o mercado de consultoria.","badge":"Líder em Escalar Consultorias"}]}'::jsonb),
(6, 'stats', 'Seu Mapa de Guerra.', '{"tag":"A Solução","subtitle":"Nossa IA não apenas coleta dados — ela mapeia seus processos e entrega os KPIs de performance que realmente importam.","stats":[{"value":"IA","label":"Cria processos, cargos e KPIs automaticamente"},{"value":"Metas","label":"Do CEO à execução, metas conectadas"},{"value":"KPIs","label":"Dashboards em tempo real"},{"value":"Processos","label":"Padrão operacional para toda equipe"}],"footer":"Tire a névoa da operação e coloque a inteligência dos dados na palma da mão da sua equipe."}'::jsonb),
(7, 'steps', 'Do caos à clareza em 7 dias.', '{"tag":"Como Funciona","subtitle":"Um método de gestão de excelência que roda sem você.","steps":[{"num":"01","title":"Diagnóstico IA","desc":"Nossa IA analisa sua operação e identifica gargalos em minutos."},{"num":"02","title":"Mapeamento","desc":"Processos, cargos e fluxos são criados automaticamente."},{"num":"03","title":"KPIs e Metas","desc":"Indicadores configurados do estratégico ao operacional."},{"num":"04","title":"Operação Viva","desc":"Equipe executa com padrão. Você lidera com dados."}]}'::jsonb),
(8, 'cards', 'É IA ou não é IA?', '{"tag":"O Diferencial","subtitle":"Conheça a Olivia — a IA do Orbit que não parece IA. Ela conversa, entende seu negócio, mapeia processos e entrega resultados como se fosse a melhor consultora que você já contratou.","cards":[{"title":"Mapeia Processos","desc":"Entende sua operação e cria fluxos automaticamente"},{"title":"Cria KPIs","desc":"Indicadores personalizados para cada área"},{"title":"Fala Sua Língua","desc":"Conversa natural, sem jargão técnico"}],"footer":"\"Aí você me diz: é ou não é IA?\" 😏"}'::jsonb),
(9, 'stats', 'Empresário consciente sabe: Liderar é gerir margem.', '{"tag":"Resultados","stats":[{"value":"+2.206","label":"Empresas usando Orbit"},{"value":"7 dias","label":"Para primeiro resultado"},{"value":"+8.000","label":"Clientes Templum"},{"value":"30 min","label":"Demonstração gratuita"}],"footer":"Recuperar o tempo perdido não é sobre trabalhar mais — é sobre trabalhar com os fundamentos certos."}'::jsonb),
(10, 'comparison', 'Pare de vender horas. Venda uma máquina de resultados.', '{"tag":"Para Consultores","subtitle":"O Orbit entrega o Mapa de Guerra que profissionaliza sua consultoria. Você para de apagar incêndio e volta a ser o estrategista que ganha pela escala.","comparisons":[{"before":"Vende horas","after":"Vende resultados"},{"before":"Operacional pelo cliente","after":"Estrategista escalável"},{"before":"Sem recorrência","after":"Receita previsível"}]}'::jsonb),
(11, 'cta', 'O ano já começou. Tá esperando o quê?', '{"subtitle":"Pare de gerir pelo retrovisor. Descubra como ter controle total com o Mapa de Guerra do Orbit.\nSem blablabla, apenas fundamentos sólidos.","buttonText":"Agendar Demonstração Gratuita","buttonLink":"/chat","badges":["100% gratuita","30 minutos","Sem compromisso"]}'::jsonb);
